server:
  port: 8080
spring:
  application:
    name: warehouse
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/warehouse
    username: dbwarehouse
    tomcat:
      initial-size: 15
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 8
      default-auto-commit: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
